language: go

sudo: false

go_import_path: github.com/myesui/uuid

go:
    - 1.8
    - 1.7
    - 1.6

os:
    - linux
    - osx

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_script:
    - gofmt -s -l -e .
    - go vet ./...

before_install:
    - go get -t -v ./...
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - go test -v -covermode=count -coverprofile=cover.out  github.com/myesui/uuid
    - goveralls -coverprofile=cover.out -service=travis-ci
    - go test -v -covermode=count -coverprofile=cover.out  github.com/myesui/uuid/savers
    - goveralls -coverprofile=cover.out -service=travis-ci

notifications:
    email: true
