language: go

sudo: false

go_import_path: github.com/myesui/uuid

go:
    - 1.7
    - 1.6
    - 1.5
    - 1.4

os:
    - linux
    - osx

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_script:
    - gofmt -s -l -e .
    - go vet ./...

before_install:
    - go get -t -v ./...
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/modocache/gover

script:
    - go test -v -covermode=count -coverprofile=cover.out -coverpkg=./...
    - gover
    - goveralls -coverprofile=cover.out -service=travis-ci

notifications:
    email: true
